### ISSUE TITLE
Implement Stack Matching

### ISSUE THREAD

**Issue by mksavic** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#108]
### Front End

Ok, so, #109 created the matching stack for each event. We need to modify the template so there are left and right buttons that signify pass/match (or whatever words/images you want to use).

### Back End

Create a model called `Matches`. It should have the following fields: `user1`, `user2`, `eid`, and `status`.

The logic is as follows:

*   If User 1 clicks left/pass, mark in the DB that User 1 passed on User 2 AND:
    *    User 2 should not appear in User 1's "match stack" anymore.
    *    User 1 should not appear in User 2's "match stack" anymore.
*   If User 1 clicks right/match, mark in the DB that User 1 matched on User 2 AND:
    *    If User 2 clicked right/match, put a Python `pass` stub since what happens after this will be completed by #110. User 2 should not appear in User 1's "match stack" anymore.
    *    If User 2 didn't click right/match, that means User 2 has not yet passed/matched on User 1. User 2 should not appear in User 1's "match stack" anymore. (User 1 should not be seeing other users in the stack who have clicked left/pass on User 1, see the first bullet.)

**Comment by jawooson** [comment]
right left + writing logic to database
