### ISSUE TITLE
Create Matching Stack for Each Event

### ISSUE THREAD

**Issue by jawooson** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#109]
### Front End

So, now that we have multiple users going to multiple events, we now need to show a user the "matching stack" for a particular event. From #107, we know that each "matching stack" exists at `/<eid>/match`. When a particular user navigates to that URL, they should be displayed the "matching stack". That is, a pile of "user cards". The "user cards" are the users that marked themselves as "Interested"/"Going" for event `<eid>`.

As for appearance, this will NOT look like `/events` (tiled cards). These cards should be one on top of the other, like Tinder. Example: https://imgur.com/a/gLaAa0m

### Back End

I don't think anything needs to be done in the back end since `interested` and `going` in the Users table are ManyToMany fields.

**Comment by vmoros** [comment]
What should happen if a user goes to the `/<eid>/match` URL for an event that they're neither interested in nor going to?
