### ISSUE TITLE
Could not sign up

### ISSUE THREAD

**Issue by dgopstein** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#138]
I tried to create an account on the site and when I would click the "Sign up" button, it would erase my password, and refresh the page. There were no warnings displayed.

![image](https://user-images.githubusercontent.com/3387679/68347135-02df4c80-00c4-11ea-9ec1-610521375d43.png)

**Comment by dgopstein** [comment]
I see now "enter a valid date" is written in small black letters. Maybe make the warning more obvious or don't refresh the page and blow away my new password?

**Comment by jawooson** [comment]
@dgopstein Noted, we'll work on it

**Comment by dgopstein** [comment]
Ok, but so I had a similar issue again this week, I have no idea what was going on, but it was complaining this date was invalid:

![19E549FB-A5EA-44E5-B6BD-0D2615192879](https://user-images.githubusercontent.com/3387679/68818410-dfcc1400-0652-11ea-9ebc-1796611112fa.png)

Changing the year wasn't enough, I think I ended up decreasing the date and month, and then that worked?

**Comment by mksavic** [comment]
@dgopstein Hi Dan, the date in your screenshot is invalid because there aren't 31 days in September. We haven't finished this issue yet but we hope to have better error messages by the end of this sprint! Thanks.

**Comment by dgopstein** [comment]
Ah, gotcha, that was dumb of me.

I definitely appreciate the desire for good error messages, but at the same time, it seems like a silly thing for your team to work on when there are actual features you could be implementing/improving.

Personally (not representative of a real user, just as the TA who needs to sign in every week), is that entry field necessary? Looking at the blank form now, I'm not sure what info it's asking for:

![image](https://user-images.githubusercontent.com/3387679/68893833-f70f0e00-06f3-11ea-9085-4b1e49744e76.png)

My assumption is that you're asking for my birthday? Is birthday necessary for this app? I tend to prefer to give as little information as possible to websites when I sign up.

Alternatively, one way to solve my personal problem would be to persist your user accounts from week to week. Then I'd never have to sign up again :)

**Comment by mksavic** [comment]
@dgopstein You make good points. I think we wanted birthday information so we could display user age on profiles.

However, we did end up fixing our DB problem this last sprint (keeping multiple migrations files). But, I suspect that we might need to reset the DB again because something was going wrong with our user avatars (they were expiring after a certain amount of time).

**Comment by jawooson** [comment]
Error message more obvious from Viktor's UI overhaul. Issue is completed.
