### ISSUE TITLE
Overall Beautification

### ISSUE THREAD

**Issue by vmoros** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#140]
### Front End
Let's make ShowUp more beautiful. Beauty is obviously subjective so this issue can't tell you exactly what to do. One specific request I have is to make margins so that pages don't go all the way to the edge of the screen. [Here](https://www.responsivemiracle.com/best-materialize-css-templates/) and [here](http://swarnakishore.github.io/MaterializeThemes/) are some ideas.

### Back End
Probably nothing

**Comment by mksavic** [comment]
I would like this issue to also include adding a template to the uploading an avatar page. Also to fix the ugly boxes on pages where avatars can't load.
