### ISSUE TITLE
Signup page Bugs

### ISSUE THREAD

**Issue by kavinshah** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#151]
1. Date of birth should not be a date in future. // can also put in more validators for minimum age
2. Email id : if a same email id is used, it should display error message rather than just refreshing page again.

can add more validations as needed.

**Comment by mksavic** [comment]
@kavinshah 

> 1. Date of birth should not be a date in future. // can also put in more validators for minimum age

Not sure what you mean by this, can you elaborate?

**Comment by mksavic** [comment]
@kavinshah Also, an issue already exists for this, #138. Can you add your notes as a comment to that issue? Closing this.
