### ISSUE TITLE
/u/<uid>: Implement "Update" text over avatar.

### ISSUE THREAD

**Issue by mksavic** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#172]
### Front End

When logged in and viewing `/u/<your uid>`, there should be some sort of "Update" text over your avatar to make it clear that by clicking on your avatar, you can edit it.

Example: https://imgur.com/5kttbGX

**Comment by vmoros** [comment]
https://mdbootstrap.com/snippets/jquery/ascensus/144008
