### ISSUE TITLE
Media/Static File Permanence

### ISSUE THREAD

**Issue by jawooson** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#177]
Heroku has "dynos." Essentially mini redeploys, it clears static and media file images in the file system. That is why some static and user photos time out. 

1. Media Files: We need to setup up a Heroku DB add on or another type of DB to store user uploaded files. 

2. Static Files: Whitenoise is a package that serves developer uploaded static files, in our case they are the background images. This needs to be deployed correctly.

**Comment by jawooson** [comment]
* [Some background on the issue](https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted)

* [Whitenoise Documentation](https://devcenter.heroku.com/articles/django-assets)

* [Heroku Addons](https://elements.heroku.com/addons)

**Comment by vmoros** [comment]
I suspect this is because of spaces in the filenames of some of our pictures

**Comment by jawooson** [comment]
https://elements.heroku.com/addons/cloudinary
