### ISSUE TITLE
Squad Requests

### ISSUE THREAD

**Issue by mksavic** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#184]
### Front End

Right now, users can add other user's to their squad by providing their email. We need some sort of request/approval mechanism so the feature isn't spammy.

### Back End

Have users send a request when an email is entered. An email is sent to that user which contains a link that they click to approve the request. Once the link is clicked, they're in the same squad. If the link is ignored, then they do not join that user's squad.

**Comment by vmoros** [comment]
From a discussion in our sprint planning, we agreed that the requests don't necessarily have to be sent via email. It would also be ok to show the requests as notifications on ShowUp itself.
