### ISSUE TITLE
"My Squad" link gives 403 error immediately after accepting squad request

### ISSUE THREAD

**Issue by vmoros** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#196]
### Steps to reproduce the error
1. Log in as some user X and add another user Y to your squad
1. Log in as user Y and click on the "My Squad" link and look at the URL. The number at the end is your squad ID.
1. As user Y, go to the "requests" page and accept user X's request. Click on the "My Squad" link and see that you get a "403 Forbidden" error. See that the URL still has your old squad ID.
1. Go to the home page and click on "My Squad" and see that the URL now has a different squad ID and that you don't get the error anymore.
![squad error.gif](https://images.zenhubusercontent.com/5d82cbfbfcb2fd0001b71738/3419e652-66db-46dd-b7a6-52ec9eafec3b)

### Desired behavior
The "My Squad" link should update immediately when you accept a squad request

**Comment by mksavic** [comment]
Fixed by PR #259.
