### ISSUE TITLE
Interested & Going functionality behaves oddly when I refresh the page

### ISSUE THREAD

**Issue by varshasivakumar** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#203]
Steps to Reproduce

1. Login as a user
2. Go to Events page
3. Mark any event as "Interested"/"Going"
4. Unmark the event (Not interested/Going anymore)
5. Refresh the page

Expected Behavior

If I have unmarked the event, it should get updated post refresh. (It still marks it as Interested/Going if I refresh the page). Vice-versa applies too.

Suggestion

I see that you are handling this call by sending a URL parameter. Instead it should be an Ajax call. That should fix this bug.

**Comment by mksavic** [comment]
I believe this is resolved by #253.
