### ISSUE TITLE
No way to see event details

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#207]
Login to the site
Go to events
Search for https://showup-nyc.herokuapp.com/events?date_range_min=&date_range_max=&genres=Jazz&genres=Classic+Rock&genres=Indie

There is a list of events. One of them "The Spill Canvas, The Juliana Theory, The Spill Canvas Sunsets & Car Crashes 15-year Anniversary Tour
Sunnyvale on Dec. 7, 2019, 7:30 p.m."  

I cant see the details of that event. Logically I would click on the card to see a details page with more information. 
This UX could be improved

**Comment by mksavic** [comment]
#59. Closing.
