### ISSUE TITLE
Stack trace shown after manipulating the ID being passed in the URL

### ISSUE THREAD

**Issue by varshasivakumar** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#208]
Steps to Reproduce

1. Login as a user
2. Mark an event as Interested/Going
3. Manipulate the URL to change the ID

Desired behavior

Should ideally not show a stack trace, any stylized Error page would be great. :)

![image](https://user-images.githubusercontent.com/45160387/69663795-fe6bdb00-1054-11ea-9449-b9c1b24ffa8b.png)

**Comment by vmoros** [comment]
We will solve this by resolving #217, closing
