### ISSUE TITLE
Events outside NY area appear

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#209]
Login to the site
Search for 
https://showup-nyc.herokuapp.com/events?date_range_min=&date_range_max=&genres=Jazz&genres=Classic+Rock&genres=Indie

There is a list of events, one of them appears to be below

The Spill Canvas, The Juliana Theory, The Spill Canvas Sunsets & Car Crashes 15-year Anniversary Tour
Sunnyvale on Dec. 7, 2019, 7:30 p.m.

Sunnyvale is not in NY area I think. Because there is no way to see the event details it is not clear that Sunnyvale is not a city in California but a venue in Brooklyn

**Comment by mksavic** [comment]
Sunnyvale is in NY (you can verify this by googling The Spill Canvas tour stops). Keeping #207 and closing this.
