### ISSUE TITLE
What's the exact purpose of the profile?

### ISSUE THREAD

**Issue by ahanif19** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#215]
Are the concerts I am attending/interested in supposed to appear below my name and favorite genres? Don't think that is happening at the moment

It seems like the profile is mainly just the text which says "X is interested in concerts" and "X is going to concerts" that I cannot edit/change? 

Sorry if I'm missing something obvious..maybe it's a browser issue on my end?

![image](https://user-images.githubusercontent.com/54873399/69667193-88b73d80-105b-11ea-9850-a862c4963948.png)

**Comment by de846** [comment]
I'm seeing this too (the interested in concerts and going to concerts, are both empty).

**Comment by mksavic** [comment]
@ahanif19 This is a bug. Thanks for catching.

**Comment by mksavic** [comment]
An issue already existed for this, #211. Closing.
