### ISSUE TITLE
Better UI page for reset password

### ISSUE THREAD

**Issue by snehalkenjale** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#219]
Can make better form UI page for reset password which aligns with other pages of the application. Can have help texts for passwords or placeholders that help user to put a strong password. 
Redirect to Login when password is updated or provide a home button.

![image.png](https://images.zenhubusercontent.com/5d8396cc1201de0001b6a107/bc88b4e0-a371-4a19-a0d7-9ba7200d5b21)

**Comment by vmoros** [comment]
Closing this issue because it's a subset of #244
