### ISSUE TITLE
Can't Logout.

### ISSUE THREAD

**Issue by utkarshp21** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#224]
## Expected Behavior
I would like to logout

## Current Behavior

Cant logout, tried multiple times
![showup-logout-error](https://user-images.githubusercontent.com/38756289/69670310-a25b8380-1061-11ea-9924-b9e98b4ba2fa.gif)

## Steps to Reproduce
1. Log in
2. Click on logout 

## Context (Environment)
Chrome latest version

**Comment by Vedanth15** [comment]
@utkarshp21 Please click on "Get me out of here" button to logout.

**Comment by utkarshp21** [comment]
@Vedanth15 Ohh, I missed that. But I think you should reconsider the UI flow for logout, other users can have the same issue too!

**Comment by mksavic** [comment]
Change "Get me out of here." to "Logout".

**Comment by mksavic** [comment]
Whoever takes on this issue: Remove this secondary logout step and just have the "Log Out" button log you out.

**Comment by vmoros** [comment]
https://stackoverflow.com/a/18135023
