### ISSUE TITLE
Too many "Rajeev"

### ISSUE THREAD

**Issue by alldne** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#226]
# Expected
When I go to matching stack, I expect same person doesn't show multiple times at a time
 
# Actual
<img width="510" alt="Screen Shot 2019-11-26 at 3 31 17 PM" src="https://user-images.githubusercontent.com/3467350/69670463-f6666800-1061-11ea-82e1-ef24782c71bb.png">

I got many "Rajeev"

# Steps to reproduce
Unfortunately no idea. I just checked my matching stack for a concert.

Maybe "Rajeev" knows what he/she did

# Note
For debugging purpose:
- Account: yj1679
- The URL was https://showup-nyc.herokuapp.com/5078961/match

**Comment by snehalkenjale** [comment]
i got this as well

**Comment by RajeevReddyIlavala** [comment]
May be I did something unintentionally, not sure what I did.

**Comment by RajeevReddyIlavala** [comment]
I figured out, since I am going to 10 events my profile is being shown 10 times

**Comment by mksavic** [comment]
#204. Closing.
