### ISSUE TITLE
Names repeating on match page 

### ISSUE THREAD

**Issue by utkarshp21** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#227]
## Description

The name of person are repeating on match page
<img width="963" alt="match-page-showup" src="https://user-images.githubusercontent.com/38756289/69670886-edc26180-1062-11ea-8fef-3eb91a798baa.png">
<img width="1268" alt="match-page-showup1" src="https://user-images.githubusercontent.com/38756289/69670890-f0bd5200-1062-11ea-97d5-47567645927a.png">

## Expected Behavior
The name on match card should be shown once

## Steps to Reproduce
1) Select events tab
2) Click on event name

**Comment by mksavic** [comment]
Issue #226 covers this exact problem. Closing.
