### ISSUE TITLE
Shows name multiple times in Matching Stack

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#228]
Login, find matching stack
https://showup-nyc.herokuapp.com/4869212/match
See broken image and name "Varsha" appears multiple times
![Screenshot from 2019-11-26 15-48-23](https://user-images.githubusercontent.com/53953892/69671515-39c1d600-1064-11ea-9267-238292690a14.png)

**Comment by mksavic** [comment]
#226. Closing.
