### ISSUE TITLE
Interested/Going events get overridden when in a squad

### ISSUE THREAD

**Issue by ppietraszko** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#234]
## Current Functionality
When I join a squad with someone my original events interested in or going to get overridden.

## Expected Functionality
I would expect the events I was still interested in or going to to remain in my options even if I joined a squad. I might not be interested in all of the events of the squad. 

## Notes
My events before joining a squad: 
<img width="1440" alt="Screen Shot 2019-11-26 at 4 51 06 PM" src="https://user-images.githubusercontent.com/54864011/69676273-624ecd80-106e-11ea-8a1f-1da01efdeedd.png">

My events after joining a squad:
<img width="1440" alt="Screen Shot 2019-11-26 at 4 52 03 PM" src="https://user-images.githubusercontent.com/54864011/69676283-68dd4500-106e-11ea-999a-33a3f7fa2bfa.png">

<img width="1440" alt="Screen Shot 2019-11-26 at 4 56 23 PM" src="https://user-images.githubusercontent.com/54864011/69676287-6aa70880-106e-11ea-890e-9cb47e8ba83a.png">

**Comment by Vedanth15** [comment]
@ppietraszko That is the idea. Once you are member of a squad, except for User Profile everything else is overridden with your squads

**Comment by mksavic** [comment]
@Vedanth15 No, this is a valid bug. I think I brought it up during the meeting yesterday. Thanks for catching!

**Comment by Vedanth15** [comment]
Maybe I misunderstood the description my bad.
