### ISSUE TITLE
Search results not saved

### ISSUE THREAD

**Issue by bhas2797** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#236]
I searched for concerts in staten island. However, the next time i check the events , it forgot my search filter and showed me all the events.

This one is when i filtered based on borough
![Screenshot 2019-11-26 at 5 48 03 PM](https://user-images.githubusercontent.com/54854035/69678950-f0c64d80-1074-11ea-8ad1-120f3f1296df.png)

Now i click on "events" my filter has now disappeared.
![Screenshot 2019-11-26 at 5 48 13 PM](https://user-images.githubusercontent.com/54854035/69678952-f58b0180-1074-11ea-986a-73a80da39a74.png)

**Comment by daisycrego** [comment]
Related: if you perform a search and then hit any of the Interested/Going buttons, the search is reset.

**Comment by mksavic** [comment]
#200. Closing.
