### ISSUE TITLE
Heroku image issue

### ISSUE THREAD

**Issue by mok232** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#237]
Image error when viewing the matching stack. User avatar doesn't seem to appear. [This](https://devcenter.heroku.com/articles/s3) might be useful.

![image](https://user-images.githubusercontent.com/40494713/69679773-fb81e200-1076-11ea-917d-f60e05cd81da.png)

**Comment by mksavic** [comment]
#177. Closing.
