### ISSUE TITLE
Image tag on profile and bio page

### ISSUE THREAD

**Issue by utkarshp21** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#239]
## Description
Seeing HTML image tag on profile page and also on edit bio page
<img width="1015" alt="Screenshot 2019-11-26 at 7 38 17 PM" src="https://user-images.githubusercontent.com/38756289/69684015-e6ac4b00-1084-11ea-8a33-172a2846d432.png">
<img width="960" alt="Screenshot 2019-11-26 at 7 37 55 PM" src="https://user-images.githubusercontent.com/38756289/69684024-edd35900-1084-11ea-930b-797337b1e13e.png">

## Expected Behavior
The bio should be blank on both the pages if user has not entered the details.

## Steps to Reproduce
1) Login
2) Click on my profile 
3) Click on add bio

**Comment by mksavic** [comment]
@utkarshp21 Did you add that image tag yourself?

**Comment by utkarshp21** [comment]
@mksavic I ran a script, that might have added it to the bio. Sorry for inconvenience, but I suggest to not take HTML tags in the bio.

**Comment by mksavic** [comment]
@utkarshp21 Security-wise, this behavior is correct. The input is being interpreted as data and not code (so this field is not vulnerable to XSS).
