### ISSUE TITLE
Sign up Functionality 

### ISSUE THREAD

**Issue by Ayushi-0903** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#240]
I am sorry for the template but couldn't find debug template.

As an user if I forget that I already have an account and I signup again, it does show any pop up saying I am an existing user.

**Acceptance criteria**
It should should that user already exist.

**Definition of Done**
When user can be informed that they already have an account.

**Comment by vmoros** [comment]
Duplicate of #212, closing
