### ISSUE TITLE
Changing ID number on user profile URL switches to other users profile

### ISSUE THREAD

**Issue by Garima2505** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#242]
## Expected Behavior
Changing Id should not be shown

## Current Behavior
The changing number on the profile URL allows switching to different user URLs

## Ideas for Improvement
Allowing users to see details of the event when opening a detail event page, like / dislike button ambiguous 

## Steps to Reproduce

1. In the user profile page, change number after u/ to any other number to see other users profile

**Comment by mksavic** [comment]
User profiles are currently public, per group decision. Like Twitter, you can access anyones page via URL if you know their uid/username. Closing.
