### ISSUE TITLE
Events Filter inputs don't persist

### ISSUE THREAD

**Issue by ab7289** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#245]
This is more minor/usability, but after filling in values in the events filters and submitting, all the values are gone. It would be convenient if those values could stick around so that if I wanted to make a slight alteration to my search query, for example look at different music genres for the same location and dates, I wouldn't have to re-enter all of the information again.

**Comment by de846** [comment]
I have this too. When I click `Interested`, my filters reset.

**Comment by mksavic** [comment]
#200. Closing.
