### ISSUE TITLE
Able to add self to squad in the UI

### ISSUE THREAD

**Issue by de846** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#246]
In the UI, I am able to add myself to the squad, in the sense that I can put my email in (which is associated with my logged-in account), and  submit without error (the page returns 200 as well). 

I think it should validate that the email in the form is not the logged-in user. 

Context: Users get confused and might think they have to put in their own email address.

**Comment by Vedanth15** [comment]
@de846 Our logic handles the scenario where you can't add yourself to the squad. We should be displaying an error message which is missing.

**Comment by mksavic** [comment]
@de846 What was shown after you added yourself? Did it redirect you back to your squad or was the page sort of just refreshed?

**Comment by de846** [comment]
I think the page just “refreshed”. I assume backend, it was a no-op, but I expected either client side validation to not allow me to submit it, or a server side response that I was doing something “wrong”.

**Comment by mksavic** [comment]
Awesome, thanks. We have #182 covering that problem.
