### ISSUE TITLE
Unable to see who I thumbs-up and thumbs-downed

### ISSUE THREAD

**Issue by de846** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#247]
I was interested in an event (Bob Dylan Date: Nov. 26, 2019, 8 p.m.) and thumbs-up and thumbs-down other users randomly. Once this is done, I don't see any way to see what I did or who they were.

I think we should be able to see at least the thumbs-up'ed users (and down too I think) so we can see who else we "swiped" on in case I want to rescind it.

**Comment by mksavic** [comment]
I don't think this is something that we planned to implement for our app, following the ideas of Tinder, Bumble, and other matching apps. Usually these apps require you to pay for a membership to rescind swipes etc.
