### ISSUE TITLE
Change Password in Account Settings Shows Incorrect Email

### ISSUE THREAD

**Issue by mksavic** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#264]
### Steps to Reproduce

1.  Log in as `vm1564@nyu.edu`.
1.  Navigate to `/settings`.
1.  Successfully change your email address to your own.
1.  Log back in, remove `vm1564@nyu.edu` from your settings, and change your password:

<img width="1280" alt="1" src="https://user-images.githubusercontent.com/15850452/70181267-98fc9780-16af-11ea-81f7-ec61f1576183.png">
<img width="1280" alt="2" src="https://user-images.githubusercontent.com/15850452/70181268-98fc9780-16af-11ea-8a99-f86abdcfd13a.png">
<img width="1280" alt="3" src="https://user-images.githubusercontent.com/15850452/70181269-98fc9780-16af-11ea-9cc0-af9577d9ee04.png">

### Expected Output

It should not say `vm1564@nyu.edu`. It should say `mksavic@nyu.edu`.

**Comment by kavinshah** [comment]
@mksavic 
It should say vm1564@nyu,edu since you used this email id to sign in for the current session.

**Comment by jawooson** [comment]
### Just tested this: 

1. I added a new email
2. Had it verified 
3. Logged out of that account 
4. Signed back in using the new email. 

Same issue. My current verified email is jwoo+6@nyu.edu and the change password page is showing vm1654@nyu.edu

**Comment by mksavic** [comment]
The issue still persists even if you log out and log back in:

![ScreenRecording2019-12-04at80719](https://user-images.githubusercontent.com/15850452/70194971-4680a280-16d2-11ea-9454-b81b25b4a778.gif)

**Comment by kavinshah** [comment]
resolved
@mksavic

**Comment by mksavic** [comment]
Tested, issue is resolved.
