### ISSUE TITLE
Events Page : More details

### ISSUE THREAD

**Issue by kavinshah** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#59]
### Front End

A user should be able to view an event description page upon clicking on an event from `/events`. The event description page is located at `/events/<eid>`.

The event description page should display the following:

1.  "Interested"/"Going" buttons.
1.  Any other information the SeatGeek's API provides about the event.

### Back End

Create a new HTML template. If we want to save information from SeatGeek that isn't already saved, the model/DB needs to be updated.

**Comment by mksavic** [comment]
@vmoros Is there enough extra information for each event from Seat Geek to warrant a detailed events view?

**Comment by vmoros** [comment]
@mksavic there is price info but I don't know if that warrants a detail view. We could also put the venue on a map.

**Comment by mksavic** [comment]
@vmoros Seems low priority. Moving to Icebox.
