### ISSUE TITLE
(4) User Profile: Photos

### ISSUE THREAD

**Issue by Vedanth15** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#63]
### Front End

When a user is editing their profile, they should have the ability to upload a max of `1` photos. Photos that are uploaded should be able to be rearranged, with their first photo being used in the matching stack. A user should also have the ability to delete a photo.

This issue is responsible for photos appearing on the user's profile, `/u/<uid>`.

### Back End

Create a new column in the `Users` DB titled `photos`. I think it will be a ManyToMany field.

**Comment by jawooson** [comment]
###Documentation for how to deploy static files for **development**. 
https://docs.djangoproject.com/en/2.2/howto/static-files/

###Documentation for how to deploy static files for **production**.  
https://docs.djangoproject.com/en/2.2/howto/static-files/deployment/

**Comment by vmoros** [comment]
Should we make it mandatory to have at least one picture?

**Comment by mksavic** [comment]
@vmoros No, I don't think it should be mandatory. We should have a default image though.

**Comment by jawooson** [comment]
I ended up using [django-avatar](https://django-avatar.readthedocs.io/en/latest/) to implement user photos.
